apiVersion: v1
kind: Pod
metadata:
  name: prisma-prometheus-sup-client
  namespace: prisma-metrics
  labels:
    app: prometheus
spec:
  dnsConfig:
    options:
      - name: ndots
        value: "1"
  containers:
  - name: prometheus-sup-client
    image: dukekautington/prisma_cloud_prometheus_client_supplemental
    imagePullPolicy: Always
    envFrom:
    - configMapRef:
        name: prom-sup-env
    ports:
      - name: prometheus8000
        hostPort: 8000
        containerPort: 8000
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service-sup-client
  namespace: prisma-metrics
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      name: prometheus8000
      port: 8000
      targetPort: 8000